### ISSUE TITLE
MV22 comms issue

### ISSUE THREAD

**Issue by fire7655** [sw4l/15thsoc#103]
Currently the MV22 seems to have a issue with interfering with communications between crew members. If you are talking between pilot and copilot using non radio comms you cant hear the other person. This issue seems to be related to the speed of the aircraft. If you are under about 80KMH you can hear fairly well. Anything higher and you cant hear each other. I am unsure if the issue is originating with interference from the map or TFAR or something else.

**Comment by Fight9** [comment]
Is this still an issue?

**Comment by fire7655** [comment]
Yes. As stated above I believe it to be a tfar issue and I believe I saw that the ch-53 has the same issue.

**Comment by MrPiipe** [comment]
https://bitbucket.org/15mod/15mod/issues/7/mv22-comms-issue
