### ISSUE TITLE
MV-22 Handling

### ISSUE THREAD

**Issue by Demix524** [sw4l/15thsoc#104]
The Mv-22 handles more like a Jet Fighter Now.  It practically completes a 360 degree roll in under a few seconds.  The Rudder is pretty much useless at higher speeds as indicated in the recent mod pack change log but this comes with a very insignificant increase to rudder rate while in helicopter mode to the point to where it doesn't really mean much this also causes us to have to pull the bird into a near 90 degree bank and turn in order to fly circles.  

While taxing and while in the air the aircraft exhibits a sort of graphical glitch in which it faces multiple directions in under few seconds before reverting to its original state.   Also while Taxing the aircraft at around 20km/h  or higher and you try to steer to the left or right, it will try to power slide and almost injuring the pilot.  

Suggestion:  Revert PBO to the one before this change.

**Comment by Fight9** [comment]
Can't win with that thing
