### ISSUE TITLE
Issue with A/T weapons

### ISSUE THREAD

**Issue by Francis-Velten** [sw4l/15thsoc#105]
If there is no backpack or platecarrier equipped, the AT-4 and the M72 LAW weapons are unable to be utilized.  The weapon while able to be equipped will not fire.  Upon checking the inventory the weapon itself appears to flash in and out of existence in the inventory (including changing the weight of the user's loadout) until a platecarrier or a backpack are equipped.  SMAW and RPG weapons have not been checked yet.

**Comment by Karneck** [comment]
Looks like it needs the room to spawn the rocket to load into the launcher. No idea how to fix this at all.
Sorry folks, just always carry a backpack I guess.
