### ISSUE TITLE
UH1Y Windscreen Glass

### ISSUE THREAD

**Issue by EvanWeeks** [sw4l/15thsoc#106]
The old glass has apparently not been restored. Or, rather, it has... it just coexists with the reflective glass. We got frustrated with the glass the other day and decided to shoot it out of the UH-1Y during training. What we discovered is that the OUTER pane (removed by a three-round burst of 5.56) is reflective, while the INNER pane is the old glass. If we remove the outer pane via the 5.56 method, we have the old glass back.

I would prefer to not have my pilots use this method of self-customizing their aircraft. It breaks immersion, to say the least, and violates a number of unit policies. The alternative, of course, is to ground our aircraft for night ops until this is fixed.

(I posted this on the former thread for this issue, but could not resurrect it on my own)

1stLt Evan Weeks
Detachment Commander
HMLA-369 "Gunfighters" (UH1Y)

**Comment by Karneck** [comment]
I did replace all the files... I'll check it again.

**Comment by Karneck** [comment]
Replaced all the files again. Seems to be fine for me, no glare issues.
