### ISSUE TITLE
AV8B GBU not laser capable

### ISSUE THREAD

**Issue by Danite1252** [sw4l/15thsoc#110]
Well, ever since ACE3 was introduced. our AV8B GBU's (Bombs) have not been laser capable like they should be.

I checked old posts including laser, AV8 and GBU and nothing came up so I'm posting one here. Plz make it work so Avengers can blow stuff up better kthxbai!

Thanks you,
2ndLt D. Hart 
Avenger Det Co.

**Comment by Fight9** [comment]
Does it work without ace3?

**Comment by Danite1252** [comment]
Used to work with AGM

**Comment by MrPiipe** [comment]
Closing since F-35 is replacing the AV-8B soon
