### ISSUE TITLE
CLS personnel unable to administer epinephrine

### ISSUE THREAD

**Issue by RobbBCO** [sw4l/15thsoc#111]
Several Sunday OPs and now FTXs (ever since ACE3 was introduced) have seen CLS-qualified personnel unable to revive unconscious people. It has been particularly disastrous when corpsmen are among the wounded, leaving no-one on the ground unable to revive.

In several instances, this has led to mass-casualty WIA events (that previously could be recovered from) into mass KIA events.

This is either through a mistake in the ACE3 medical settings on the template, by an unknown bug or by a decision I am unaware of. 

At the very least, ACE3 medical settings need to have the medic-restriction for certain items' use turned off, so that CLS-qualified personnel are able revive downed corpsmen and/or stabilise unconscious people and avoid the bleedout timer.

Robb
Haymaker 1

**Comment by Fight9** [comment]
We are trying to find the best solution to this. Stay tuned.

**Comment by jdh0221** [comment]
Being a pilot and previously a corpsman. This would be great!

**Comment by MrPiipe** [comment]
AMS was rolled out
Anyone can use injectors.
~Closed
