### ISSUE TITLE
No Flares in MV-22 when you have a CP

### ISSUE THREAD

**Issue by jdh0221** [sw4l/15thsoc#112]
Tonight during the FTX I was shot at a couple times and did not have flares at all. Upon further testing, I could get into the aircraft and it would show Semi with 300 on board. However, when my CP got it. I lost them completely. The name and count disappeared. All I saw in the box was the laser marker. He got out again and then they reappeared.

**Comment by armyinf0703** [comment]
Did the CP have access to the flares?

**Comment by jdh0221** [comment]
I asked him to hit the "C" button to test if he could deploy them and he
could not. I took screen shots of my flares being there and then removing
themselves from the weapons box if you wanna see.

**Comment by MrPiipe** [comment]
https://bitbucket.org/15mod/15mod/issues/6/no-flares-in-mv-22-when-you-have-a-cp
