### ISSUE TITLE
MV-22 Box Unloading Issue

### ISSUE THREAD

**Issue by jdh0221** [sw4l/15thsoc#113]
Tonight I picked up 3 crates. Flew them to the LZ and when I landed I only had an option to "Unload All". It's the first time I have seen it not give both options. The back box went out of the ramp. Then back in and repeated twice. Which in turn made my aircraft explode killing everyone inside. I had 6 GCE in the back which I had stay there while I unload so I wouldn't kill anyone.

**Comment by MrPiipe** [comment]
Probably related to desync or physics issue since it has only happened once.
