### ISSUE TITLE
Request from G4 - M240 Recoil

### ISSUE THREAD

**Issue by Karneck** [sw4l/15thsoc#114]
Request from Gambler 4 HQ.
Gunners are reporting extreme difficulty shooting targets past 600-700m, the recoil is far too much to handle even with a bipod. Suggesting working with the recoil so gunners are able to shoot up to 1000m.

Capt D. Schultz
Company Commander
Echo Company

**Comment by MrPiipe** [comment]
New M240. Hopefully the issue doesn't happen in this one too.
