### ISSUE TITLE
AMS - die when all wounds bandaged

### ISSUE THREAD

**Issue by AaronSmithee** [sw4l/15thsoc#115]
two different cases:

case 1:  all wounds bandaged, person still has pain indication (flashing white on edges of monitor), person is revived - able to walk/run, but still dies 

     - Is it that not having pain stopped is keeping the death timer running?
     -  Is it that bandaging the wounds does not stop the death timer?

case 2:  all wounds bandaged, person cannot be revived (no corpsman to administer Epi short), then dies.  There is a heart rate and blood pressure, though the Blood Pressure may be low.

       - may this be addressed by stopping and administering CPR to extend the timer?  will test this in Fire Team training  

The two cases both had wounded in pain - not sure if that is a factor for the death timer or not.

**Comment by J-Ziegler** [comment]
Any known way to reproduce? If so, we should get together to see if it's still an issue with updated ACE3 and, if so, talk to their people. If not, all should be well so long as we update before moving over to AMS next month.

(Not mod team)

**Comment by MrPiipe** [comment]
Pretty much what J-Ziegler said. Make sure to test this with the latest ACE update, we haven't updated ours but it will be updated for when AMS is implemented. If this issue still happens with the latest ACE update, make sure to post it on their Github page: https://github.com/acemod/ACE3/issues

I will leave this open for now as a reminder, I will close it soon if nothing develops.
