### ISSUE TITLE
Tweak or Replace current Abrams and RG 31s

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#120]
Current Abrams is 220MB
Current RG 31s are 220MB

Too damn large.

**Comment by screech02** [comment]
RG31 are essential for EOD personnel. Primarily the GyroCam (GC) versions. 
the RG33 in the RHS leaves much to be desired although it is significantly smaller. 
I have compared them in a driving course referenced here: https://youtu.be/sY52Oc5FPpk
