### ISSUE TITLE
Merge in-house configs into meu_blufor

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#123]
Consolidate our config fixes into 1 PBO

- [x] titanfix.pbo
- [x] 15thintel.pbo
- [ ] dar_mtvrMEU.pbo
- [ ] task_force_radio_15th.pbo Maybe
- [ ] task_force_radio_items_15th.pbo Maybe

**Comment by MrPiipe** [comment]
Update, Titan's CO has requested that Burnes Abrams be replaced with RHS' when we overhaul the mod pack. titanfix is no longer needed so it can be removed from meu_blufor.

**Comment by armyinf0703** [comment]
IF overhaul is approved by CS of course

**Comment by Fight9** [comment]
I'll make multiple branches. I will need to figure out who made the tfar items, too.
