### ISSUE TITLE
Texture issues with OPFOR Vehicle

### ISSUE THREAD

**Issue by VictorMcGalrish** [sw4l/15thsoc#129]
I'm unsure if its local mod issue or general, but I just realize that some vehicle in the OPFOR pack currently have some texture bugs ( black/white and invisible part) on some of the vehicle. This was Seen ON BMD-1 and BMP. Might want to take a look at that.

I'm still unsure if its only local but myself and one of my guys saw that in our training today.

Sgt H. Mitchell

**Comment by MrPiipe** [comment]
I'll check on it. 
Never seen these issues and I use the BMPs and such as Zeus during operation.

**Comment by VictorMcGalrish** [comment]
I have made another test, everything is good again. Probably a fail in loading the mod. You can close this.
