### ISSUE TITLE
Request from Weapons Platoon

### ISSUE THREAD

**Issue by Karneck** [sw4l/15thsoc#131]
Approved by both Echo and Foxtrot CO's

Please add in a 200 round box.

Code is all here for you to use.

	class MEU_200Rnd_M240_762x51: MEU_100Rnd_M240_762x51
	{
		mass = 67;
		count = 200;
		descriptionshort = "Caliber: 7.62x51mm <br />Rounds: 200<br />Used in:M240";
		displayname = "M80 Linked 200rd";
		initspeed = 833;
		lastroundstracer = 3;
		tracersevery = 5;
	};
	class MEU_200Rnd_M240_762x51_T: MEU_100Rnd_M240_762x51_T
	{
		mass = 67;
		count = 200;
		descriptionshort = "Caliber: 7.62x51mm Tracer<br />Rounds: 200<br />Used in:M240";
		displayname = "M62 Linked 200rd";
		initspeed = 833;
		tracersevery = 1;
	};

**Comment by Absolution15th** [comment]
Ammo box requests go here:
http://15thmeu.net/forums/index.php?topic=12836.0

Identify the crate, the item, and quantity or the request will be rejected.

**Comment by MrPiipe** [comment]
After reading the request I noticed it isn't a new item for the box. It's to create a new item. I'll re-open it and it will be added for the overhaul.

**Comment by Karneck** [comment]
Was going to say.... Thank you.
