### ISSUE TITLE
Spontaneous KOs

### ISSUE THREAD

**Issue by SamMooney** [sw4l/15thsoc#137]
Sat on a corner for a little bit, average Rifleman loadout at around 30kg. Ended up getting KO'd twice, taking damage to only the torso each time I woke back up.

Seemed at the time like it was to do with a lack of air because I was holding my breath while zooming/steadying for a fair while on said corner. Avoided zooming/holding breath for the rest of the op and never ran into the issue again.

**Comment by MrPiipe** [comment]
Mmm, interesting. I'll do some tests and see if I can reproduce it.

**Comment by MrPiipe** [comment]
Haven't been able to reproduce it, might be a one time thing or just Arma's new stamina system.
