### ISSUE TITLE
Weird ACE3 no interact bug

### ISSUE THREAD

**Issue by LilChillbil** [sw4l/15thsoc#138]
was corpsman all night, one guy I couldn't see his name couldn't interact with him but he was down. Not sure if it was an issue on his end but never seen this bug before and will most likely never see it again.

**Comment by MrPiipe** [comment]
Really weird bug, happens every now and then. Most likely some collision issue of some sorts but it's essentially impossible to fix on our end, it's either ACE3's or ArmA's fault.
