### ISSUE TITLE
Fun OP 12/13/15 Reported Weapon Bugs

### ISSUE THREAD

**Issue by RJohnson15MEU** [sw4l/15thsoc#140]
1. RHS explosives not working with ACE.

2. 4-1/4-2 Load-out weight is off I.E Can't run as far as they used to.

3. 4-1 MG Cone of fire is not correct

4. 100 Round MG boxs displaying as 100 Round box but are Really 50 Round.

Thanks

**Comment by armyinf0703** [comment]
1. Can be fixed
2. Please be more specific
3. Compared to old how is it?
4. Fixed with 200rd

**Comment by RJohnson15MEU** [comment]
1. Thanks look forward to the fix
2. 4-1/4-2 weights as I.E. Old MEU Mod pack use to run about say 1mile for this example but with new MEU RHS mod pack can only run about half.
3. Compared to the Old one is this great it more once it gets out to the 400-500 range.
4. Great Thanks


Thanks again for the fast work to forward to the updates.

**Comment by armyinf0703** [comment]
2. I would blame the new Stamina system, but lets keep an eye on it and see,
3. I am still confused, is the accuracy worse or better than the CUP M240?

**Comment by RJohnson15MEU** [comment]
OK

and Better then the CUP M240

**Comment by armyinf0703** [comment]
If you have the old mod pack, can you do some testing and check the stamina, with the old pack to the new? Try and match the same loadout, see if their is a difference with the update.

**Comment by RJohnson15MEU** [comment]
Rgr 

Thanks for all your help and fixs.
