### ISSUE TITLE
QA Test Server ACE Rotary Slot Issue - LHD Missing

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#143]
Felt better of posting this issue in QA test server thread, so I'm posting the issue here instead.

Hopped on to the QA server for some fiddling, but running into an issue with some of the ACE slots in the server.

Seems the intent was for rotary members to spawn on an LHD, but no LHD asset seems to be present when I enter the mission as a member of ACE rotary (Gunfighter, Warhorse, etc.). Players entering the mission in ACE rotary slots that are presumably assigned to the LHD will fall into the ocean in open water.

I'm currently running the mods associated with 15th V4.0.2 (15thV4, 1thACE_Test, RHSUSAF v0.4, RHSAFRF v0.4, AiA, CBA_A3, TFAR, STHUD) but I was encountering this issue using V4.0.1 last night as well.

The attached on-screen error may be associated with the issue.
![testservererror](https://cloud.githubusercontent.com/assets/13390814/11905395/ed91e046-a58b-11e5-8621-85c8958bd72a.png)

**Comment by MrPiipe** [comment]
The mission that was being used had the old LHD, current mod pack has a new LHD. 
You also went into another server (Velten's) and not the one we directly manage (C. Johnston's).

**Comment by CandidYams** [comment]
Gotcha, I'll use the other server then. I just picked the first one listed.

**Comment by CandidYams** [comment]
Er, did not mean to close this issue. :/

**Comment by MrPiipe** [comment]
I'll have a mission ready in the S-4 Mod Team Server 15thUNOFFICIAL soon, it will be in the map for this Fun Op.

**Comment by MrPiipe** [comment]
I don't see anyone else having this issue. Like I said, it was most likely the mission that was made with the previous LHD, closing this
