### ISSUE TITLE
RHS UH-1 + 15thV4.0.2 Model Conflict

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#144]
Summary:
RHS UH-1 asset appears to have some severe model anomalies when loaded in with RHS_USAF v0.4 and the current iteration of the 15thV4 test mods. First impression seemed to indicate a conflict between the 15th UH-1 in @15thV4 and the UH-1Y asset present in RHS. This issue did not occur when running RHS without @15thV4. See attached image.

To Reproduce:
Mods: @15thV4 (v4.0.2), @15thACE_Test, @RHSUSAF (v0.4), @RHSAFRF (v0.4), AiA (v1.4.1), @CBA_A3 (v2.2.0.151130), @TFAR (v0.9.8.2), @sthud_a3 (v14.3.2.1)

Loaded USA (USMC - W) ---- UH-1Y (FFAR/MG) in Editor for function testing on Stratis.

Solution:
Removing UH1Gungither.pbo from @15thV4 cleared this issue up straight away.

![uh1_clipped_model](https://cloud.githubusercontent.com/assets/13390814/11906060/948cc25a-a58f-11e5-995d-2411e97086ed.png)

**Comment by MrPiipe** [comment]
They look fine on my end.
Spawned: The 3 RHS UH-1Ys and our UH-1Y
![107410_2015-12-18_00001](https://cloud.githubusercontent.com/assets/5787557/11906372/f28c7ad0-a599-11e5-8a5e-0e1dd7091b88.png)
![107410_2015-12-18_00002](https://cloud.githubusercontent.com/assets/5787557/11906373/f45d6126-a599-11e5-9042-4af1edb48486.png)

Might be the mission/server as I had mentioned earlier or it might be that your modpack is corrupted somehow(?)

**Comment by CandidYams** [comment]
Restored UH1Gunfighter.pbo

Placed both UH1s into editor. 15th UH1 appears fine, but the RHS UH1 is having same issues as pictured in my original post. It's troubling that this issue seems confined to me so far. I will attempt working it on my end for now, but all I can really do is delete and reinstall the modpack or Arma 3.

**Comment by MrPiipe** [comment]
Did you download RHS with the updater or the torrent? It could just be RHS, but if it works when you remove the Gunfighter pbo from our pack then it could be our pack. Really weird issue but haven't seen anyone have this issue, some people were testing helicopters yesterday completely fine.

**Comment by CandidYams** [comment]
Deleted associated mods (15thV4, 15thACE_Test, RHSAFRF, RHSUSAF, CBA_A3)

Redownloaded 15thV4, 15thACE_Test, CBA_A3 via http://15thmeu.net/forums/index.php?topic=45670.0

Unpacked RHSAFRF and RHSUSAF again from existing torrented copies.

Ran the same scenario with the RHS UH-1Y  and 15th UH1Y without conflict this time. 

I can't really say what was different between the state of my addons before and after deleting and redownloading them, but the issue seems resolved. Good to know it was an issue on my end and not something that would have required fixing with the mod pack.

**Comment by MrPiipe** [comment]
Yeah, that made me panic :stuck_out_tongue: 
Thankfully you were able to fix it
