### ISSUE TITLE
Fun OP 12/20/15 Reported Weapon Bugs

### ISSUE THREAD

**Issue by RJohnson15MEU** [sw4l/15thsoc#145]
1.) No SMAW tracer round in the box

2.) No Basic arma range finder

3.) 4-2s 40KGs weight they are reporting that they cant run very far. ( Ill look into getting more info on this).

4.) Cant run at all with two rockets in there Backpack

5.) Cant Carry or drag downed People.

6.) No Smoke for M32 and No Black Smoke

7.) AN/PVQ-31A Cant Read the Ranges.

8.) Range on M32 is down 375 from 400

Thanks Again

**Comment by armyinf0703** [comment]
The weights/ running is all the new stamina system, we have zero control over that, the heavy you are the less you can run, but vs the old system, you can walk forever (to my understanding)

M32 smoke/ Black smoke will be fixed once the RHS Propsal is finalized/ approved. If its not approved, it doesn't make sense for us to make those happen.
5. Could you be more specific/ provide video?
7. Could you be more specific?
8. I tested and was able to get 400, but I will test again- Note 2nd test it reaches out to 400, but only zero's to 375, I will look further into this

**Comment by MrPiipe** [comment]
5. Is it that you can't drag/carry people? Or that they teleport when you drag/carry?

In regards to weight/stamina, it's something that would be a lot of work on our end to change the weight of every item. Our only hope right now is that ACE 3 releases the legacy stamina from before the update, but that might take some time.

1 and 2 are mission issues that were my fault and overlooked.

**Comment by RJohnson15MEU** [comment]
On 1. it was the teleporting again

and np ill hope for Ace 3 lol

Thanks
