### ISSUE TITLE
FunOp 12/20 - Utility trucks not functioning for ACE assets

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#146]
RHS v0.4 UH-1Y had no luck engaging commands off any of the three utility (repair, rearm, fuel) trucks that were placed on the Nimitz during the FunOp.

Attempted taking 'ownership' of each of the utility trucks by hopping into the driver's seat and returning to the UH-1 to try to get them to work, but no suck luck.

Avenger was also unable to use the rearm truck on the Nimitz. Unsure of Avenger working with the other trucks or Viking's attempts to rearm.

**Comment by CandidYams** [comment]
Unsure if ground assets are affected by this issue, but that might be of concern for the larger test in January involving Titan and Gator.

**Comment by MrPiipe** [comment]
I believe ACE disabled the use of the utility trucks unless there's an ACE (Rearm, refuel, repair) module. I will test it and check if that's the issue.

**Comment by MrPiipe** [comment]
Transferred to https://bitbucket.org/15mod/15mod/issues/4/funop-12-20-utility-trucks-not-functioning
