### ISSUE TITLE
FunOp 12/20 - Red Dragon does not like the LHD deck

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#147]
The MV-22s placed on the deck of the LHD for the test mission were tumbling end over end where they were placed. Shooting them did not yield any pretty fireworks, but they are pretty scary to watch. I did not attempt to get into them.

Zeus (Donando, I think) ended up deleting the MV-22s before the operation started.

Sadly, I do not have any screenshots of the incident available. However, the effect should be reproducible by reloading the mission used for the FunOp and spawning on the LHD as an ACE member.

**Comment by MrPiipe** [comment]
Yeah it was weird that it was happening, I'll conduct some testing to check if it was a one time thing or if it was related to the height it was spawned.
It also seems to only happen in a multiplayer environment since it never happened in the editor.

**Comment by fire7655** [comment]
I believe the last FTX before WSD we had the same issue happen. It only occurred with the MV-22 located at the rear of the ship.

**Comment by MrPiipe** [comment]
Seems to not be related to the new LHD but the rear end, possibly height issue.
