### ISSUE TITLE
OPFOR has no NVGs

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#148]
For some reason, OPFOR have no NVGs.

**Comment by armyinf0703** [comment]
Because Russia realistically does not have NVGs

**Comment by armyinf0703** [comment]
I'll add to that, they have NVG tanker helmets and scopes for weapons but don't make and issue  NVGs like the US army/ USMC does that fit on any helmet

**Comment by MrPiipe** [comment]
Pending decision by Command Staff if we should add them or not.
Transferred to BitBucket
