### ISSUE TITLE
Cant enter/exit vehicles; AGM issues

### ISSUE THREAD

**Issue by PvtSchrock** [sw4l/15thsoc#48]
I would walk up to a vehicle and scroll wheel "get in".  It would go through the animation but then I would be outside the vehicle in the same spot.  

Any AGM action on me would also be bugged.  Instructor tried restraining me, but then could unrestrain, but could tap me on the shoulder.  Any attempted medical diagnosis would come back all white, while I was still on the ground bleeding out.

I have a 10mb conection, and ping is in the 40s.

**Comment by Karneck** [comment]
I'd say make sure you were running the correct version of the 15th Pack on both the server and for everyone else in it.

Attempt to repeat the issue and get back to me with the details. If I don't hear from you in a week I'll close this issue.

**Comment by PvtSchrock** [comment]
Just reDLed the mod packs and reinstalled ARMA.  Joined the recruiting server, was fine for about 2-3 min.  This is where things get weird.  I had gotten in and out of a quad bike few time testing to make sure everything was working then walked over to the one next to it and couldnt get in, but I could still get in and drive the one that I had been messing with. Did some more experimenting, but everything else was messed up, couldnt enter any other vehicles ecpt the one quad, couldnt pick up anything from the gear box, and the AGM interactions were screwed up.  I have a 10mbs connection, my ping was at 42, and my bandwidth was in the 1000s.

**Comment by PvtSchrock** [comment]
I redownloaded CBA,  now everything works perfectly for about 30min to an hour, then bugs out.  Also have some new developments, I cant interact with others via AGM, and I mag dumped an enemy dropped a 203 at his feet and he didnt die.

**Comment by PvtSchrock** [comment]
Problem resolved.  The wireless router I was using was interfering with my connection to the servers.

**Comment by Karneck** [comment]
Issue resolved by repartee. Closing.
