### ISSUE TITLE
15th Vechicle Loadout Box Dosnt work

### ISSUE THREAD

**Issue by CplMcMillan** [sw4l/15thsoc#49]
as the title says curently it dosnt work but more importantly i know y and how to fix it this is missing from the meu_ammoBoxes.pbo config.bin file

class CfgNotifications {
	class meu_vicCrates {
		title = "15th Vehicle Crate"; 
		iconPicture = "%1"; 
		iconText = ""; 
		description = "%2"; 
		color[] = {1,1,1,1}; 
		duration = 3;
		priority = 0; 
		difficulty[] = {}; 
	};
};

i have a config.bin with it added that works if needed.

**Comment by Fight9** [comment]
Some one merged the config into one but left that entry out. I'll update it tonight. 

If someone wants to get to it first, this needs to be added to the config.cpp

class CfgNotifications {
#include <\meu_ammoBoxes\vehicle\vehicleCfgNote.hpp>
};

**Comment by Karneck** [comment]
Gunny Philips placed the notification back in. Closing this issue.
