### ISSUE TITLE
Not hearing friendly fire

### ISSUE THREAD

**Issue by tamouleo** [sw4l/15thsoc#51]
When my team fire, I can't hear the sound of there weapon. I hear mine and we are using the same weapon. Also, I can hear the ennemie's weapon when they fire. This is on 15thmeu mod pack. In the 15threcruite mod pack, I can hear the sound of my team.

It seems like its only on the bravo server cause I was playing on a training server with the official 15thmeu pack and I was able to hear friendly fire.

**Comment by Karneck** [comment]
It's an issue that not very many people in the unit experience. There are already several issues in the help desk. - http://15thmeu.net/forums/index.php?topic=33009.0

In there are some fixes that some have used. Commonly, updating your CBA or a re-install of ARMA.
