### ISSUE TITLE
UH1Y/AH1Z too fat for sling

### ISSUE THREAD

**Issue by Medic1334** [sw4l/15thsoc#52]
The H1 airframe is too heavy for the -49 to slingload.  It hooks up but when you attempt to lift it you go nowhere, even at full collective and trying to get a "running start" to it. Suggest lowering the weight value of the H1 airframes to allow this unless it throws other things off.

**Comment by Karneck** [comment]
There is no issue. It works fine. Insure your pack is up to date and the server you are on is up to date.
