### ISSUE TITLE
Explosions dont appear in thermals AH-1

### ISSUE THREAD

**Issue by Medic1334** [sw4l/15thsoc#54]
When using the cannon on the AH-1 there is smoke generated but no explosions.  If we are simulating using nothing but AP rounds then I understand, but http://en.wikipedia.org/wiki/M197_electric_cannon shows that the only tracer rounds being used in the cannon are HEI-T so we should be seeing a good pop of "hot" when the rounds impact.

I am unsure if this is a camera issue or a munitions issue. Most likely a munitions issue. Not high on the list of priorities, but possibly is one nonetheless.  You can see video of me employing the cannon and not seeing any heat from the explosions here: https://www.youtube.com/watch?v=7s37DZRwdQo&&t=50s

Also FWIW the tracers arent showing any heat on them as they go through the air, but thats really nitpicky

**Comment by Karneck** [comment]
Pretty sure this was ARMA being ARMA, however I will look into it. Thanks for bringing it to my attention.

**Comment by Karneck** [comment]
no longer interested in fixing
