### ISSUE TITLE
OpFor has 2 sets of NVGs

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#55]
As title says it, if you remove NVGs using ARES, Benzeen army still has another set of invisible (No icon) NVGs that go into their binoculars slot.

**Comment by Karneck** [comment]
Provide video or screen shot please. Don't understand how NVG's fit in bino slot.

**Comment by MrPiipe** [comment]
http://imgur.com/a/nKfX4#0

**Comment by PezD** [comment]
I'll see about fixing this. Very strange. Possibly an issue with AGM_NightVision as it changes the classnames in some way.

**Comment by Karneck** [comment]
Switching to ACE. maybe it'll fix it.
