### ISSUE TITLE
NV shows troops as blinking

### ISSUE THREAD

**Issue by Medic1334** [sw4l/15thsoc#56]
See: https://www.youtube.com/watch?v=APZd7vsWYEk

Infantry appear to blink under NV.  Issue was seen by pilot with NVG's and me under the scope.  Might be something with our models?

**Comment by Karneck** [comment]
models are whatever is in ARMA 3 so would be a BI issue.

Only other thing I can think of is their clothing or weaponry.

**Comment by Karneck** [comment]
switching to ACE. Lets see if that fixes it.
