### ISSUE TITLE
New ACOG zooms completely break BDC

### ISSUE THREAD

**Issue by AdmiralKarelia** [sw4l/15thsoc#57]
The ACOG's bullet drop compensator was useful for hitting targets at range as well as for getting a rough estimate of the target's distance. After several tests on the Stratis runway, I can now say with certainty that the new ACOG is completely broken in this regard, as the scope was re-zoomed without changing the BDC, and for example, targets at 500m out are now unable to be hit at the 500m hashmark, and the BDC "ladder" is entirely misleading as to distance.

**Comment by Lukev221** [comment]
When watching this video look at the distance set on the weapon when the scope is on and off of the weapon.  I am also unable to change that value when the scopes are on the weapon systems.  The following video shows the ACOG scope and the scope used for the M240B. https://youtu.be/9MhLJ3gwKBY

**Comment by Karneck** [comment]
*sigh* this is what I get for not testing this with AGM.

**Comment by Karneck** [comment]
Switched to ACE. Will have to completely re-do optics.
