### ISSUE TITLE
Sound change suggestion: M27 M240 swap

### ISSUE THREAD

**Issue by J-Ziegler** [sw4l/15thsoc#58]
Haymaker 4-1 suggested that the sound files for the M27 automatic fire and M240 (M249 as well?) be swapped. 4-1 believes that the sounds would be more appropriate for the larger weapons. The M27 when in full auto seems much louder comparatively. Told to make an issue tracker here, posting on their behalf.

**Comment by Karneck** [comment]
Already slotted for changes.

**Comment by Karneck** [comment]
Implemented
