### ISSUE TITLE
UAZ on Blueforce Tracker

### ISSUE THREAD

**Issue by connor0095** [sw4l/15thsoc#59]
If I place an empty UAZ and put Greenfor units into it the vehicle pops up in CTAB. If they dismount the marker disappear.

**Comment by Karneck** [comment]
If green was set to be friendly to "Blue" they would show up on the CTAB marker. That's mission settings, not a bug.

**Comment by connor0095** [comment]
Only in vehicles did they pop up. Does the UAZ have a built in CTAB?

**Comment by Karneck** [comment]
All Car class's have a built-in CTAB. It's how it's coded to work.
