### ISSUE TITLE
RG31 Weapons Ranging (m2 is fixed. MK19 needs work)

### ISSUE THREAD

**Issue by Medx-a99** [sw4l/15thsoc#61]
Ranging on RG31 turret ranging is not correct

**Comment by Karneck** [comment]
Corrected the M2 ranging by adjust the model P3D weapon sight. 

The mk19 has no workable ranging system and my minor attempts at creating one have met with failure. I'll leave this issue as open for now.

**Comment by Karneck** [comment]
Got the bitches to lie down and take it in the ass.

Also added a Weapon Safety
