### ISSUE TITLE
AAV ACE3 FCS/ ACE3 Interaction

### ISSUE THREAD

**Issue by Alpha234** [sw4l/15thsoc#62]
Requesting that the AAV be updated so we can load prisoners/casualties into the vehicle.
Also requesting that FCS be updated so we can utilize all of the features that ACE3 offers vehicles

**Comment by MrPiipe** [comment]
Did you try loading prisoners on the AAV with ACE? It used to work with AGM

**Comment by Karneck** [comment]
FCS shouldn't be too much of an issu.e The prisoner interaction is a different ballgame, we'll look into it.

**Comment by Karneck** [comment]
No issue found
