### ISSUE TITLE
Suppressors not working

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#63]
Suppressors do not work for M16 or the Mk12 and of course the M4 does not take a suppressor. M27, M110 and M40A5 suppressors work.

**Comment by Karneck** [comment]
My mistake with JointRails when updating to ACE3 code. Will be fixed next update.

**Comment by armyinf0703** [comment]
Just asking here as its easier..Do you need me to remove the BiPod for M27 so it can use normal A3 bipods?

**Comment by MrPiipe** [comment]
That would be great!

**Comment by Karneck** [comment]
Fixed
