### ISSUE TITLE
Unarmed HMMWV's arent rendered as objects from the "Stand-up" position.

### ISSUE THREAD

**Issue by Luftwolfe** [sw4l/15thsoc#64]
The roof of the HMMWV isn't considered a valid object, and therefore makes it impossible for any gunner to deploy/rest their bipod/barrel to steady the fire while on the move.

Not sure if this is intentional or not, but I figured I would post this as a bug to possibly make the unarmed HMMWV variants more viable for small scale (fire team/squad) trainings.

**Comment by Karneck** [comment]
Not a bug. Working as intended. You can't do this with any other A3 vehicle.
