### ISSUE TITLE
MV22 Walkway seats

### ISSUE THREAD

**Issue by RSFHorn** [sw4l/15thsoc#67]
MV22 walkway position options are removed from the scroll wheel menu if any other position is chosen other than "ride in back". Including other walkway positions

If somebody enters any walkway seating position, the scroll option disappears from all other seats. 
If somebody enters the left/right passenger slot, the scroll option disappears from all other seats. 
If somebody enters the pilot/copilot slot, the scroll option disappears from all other seats.

The only options available to the people still in the passenger positions  after any of the other slots are filled are "Get Out" "Eject" and "Inventory". The person occupying any of the Walkway or left/right passenger, or co/Pilot positions still has access to all the scroll menu options they should.

As soon as any of the aforementioned slots are vacated, the scroll options re-appear for everybody else who is supposed to have them.

**Comment by Karneck** [comment]
Thanks for bringing this up. I'll look into it

**Comment by Karneck** [comment]
closing, not able to find any issues with it.
