### ISSUE TITLE
RG31 Collision with Humans

### ISSUE THREAD

**Issue by Sellers15th** [sw4l/15thsoc#68]
When driving the RG-31 equipped with the gyrocam and M2, I attempted to run over an enemy footmobile standing in the middle of the MSR firing at us. The vehicle passed through the enemy without harming him, and severely injured a passenger seated in the rear of the RG-31- the passenger having apparently struck the enemy as he passed through the vehicle.

**Comment by Medx-a99** [comment]
collision protection for occupants has been increased to be in line with MTVR and previous MaxxPro.

Unable to recreate issues with RG-31 failing to injure or kill enemy infantry upon collision. Possibly related to desync/lag.

1stLt Sellers, Was this on a dedicated server or a local test on your client?

**Comment by Sellers15th** [comment]
Dedicated LCE Unofficial server. The enemy in question was FIA. I'll hop on today and try to recreate the issue again.

**Comment by Medx-a99** [comment]
1stLt Sellers,

Were you able to recreate this?

**Comment by Karneck** [comment]
Not able to recreate, no further comments made from author of report. Closing.
