### ISSUE TITLE
RG31 Collision with Objects

### ISSUE THREAD

**Issue by Sellers15th** [sw4l/15thsoc#69]
I witnessed an RG-31(A) back into another RG-31(B) slowly, from about 6ft ahead in line, destroy the front-left tire and kill two people seated in the RG-31(B). Additionally, I drove my RG-31 into a small bush that I've passed through before on just about every other vehicle type in Arma with no issue, but received light injuries from the bush. Testing it out to be certain the bush in question wasn't just an oddball, I was able to replicate the injury on multiple other plants that can be overrun without issue by any other vehicle.

**Comment by Medx-a99** [comment]
collision protection for occupants has been increased to be in line with MTVR and previous MaxxPro.
