### ISSUE TITLE
RG31 Back-Door Instant Reload

### ISSUE THREAD

**Issue by Sellers15th** [sw4l/15thsoc#70]
When seated in the back of the RG-31, you can open the rear door and fire your weapon out the back. The problem is: whilst firing from this position, you can fire continuously in full-auto and simply tap your "reload" key to instantaneously, and without interrupting fire, reload your weapon. The reload sound plays, but there's no reload animation, and your magazine is instantly refilled.

**Comment by Karneck** [comment]
Never heard of this happening before. I'll look into what the current config is set up for.

**Comment by MrPiipe** [comment]
I think this was happening for the Offroad too on FFV positions, could be wrong. I do remember that when reloading the animation didn't happen, possibly a missing animation or code on the CUP weapons?

**Comment by Karneck** [comment]
Reload animations are based off the A3 animations. Wouldn't be our fault, would be BIS's.

**Comment by Karneck** [comment]
Was only happening with the M4/M16 weapons. It's been fixed by adding the proper reload gesture animation. For some reason, one wasn't defined.
