### ISSUE TITLE
MV-22 Collective Power Adjustment

### ISSUE THREAD

**Issue by jdh0221** [sw4l/15thsoc#71]
At full throttle the MV-22 lifts at a slow rate when in hover mode. I would say about 1 1/2km a second. That's a rough estimate but close. 

It also descends at a very slow rate as well. Both moving and hovering. This has been looked at by Turtle and the mod seems to of broke trying to adjust it.

**Comment by Karneck** [comment]
Pretty sure thats just how ARMA 3 is. I'll look into it.

**Comment by Karneck** [comment]
Sadly I don't think there is an option. It's considered a "plane" class in ARMA. The VOTL option just adds auto-hover but doesn't provide any options to fine tune the power of it.
