### ISSUE TITLE
MV-22 Rudder Sensativity

### ISSUE THREAD

**Issue by jdh0221** [sw4l/15thsoc#72]
When in a hover mode the mod turns like a fat pig. You can even angle the aircraft as to help with momentum and still turns extremely slow. If you compare our to RL there is a hug difference. I was wondering if more response could be give to the control?

She doesn't need to whip around like a helo because obviously she doesn't have a tail rotor.. But she still moves a lot faster in RL.

**Comment by Karneck** [comment]
Easy fix, will adjust.

**Comment by Karneck** [comment]
I've adjusted the Rudder affect, however it open affects it in flight mode unless you are exceeding 200 kph, in which cause Rudder becomes useless (Its an arma thing). This doesn't affect Auto-hover mode, or at least not from my testing with jacked up properties.
