### ISSUE TITLE
MV-22 Cargo Lights

### ISSUE THREAD

**Issue by jdh0221** [sw4l/15thsoc#73]
When testing we noticed that then you enable red and then go to green. They both stay on. I was wondering if there was a way that once green was enabled or vis versa. That the other would shut off. While 2ndLt Gage and I were testing I was having to fly.. Scroll wheel red on... Then scroll wheel to turn off red and then scroll to turn green on. If you turn green on and not red. They are both on at the same time. I know this seems picky but it's better to not have confusion in intense situations.

**Comment by Fight9** [comment]
Adjusted. Turning a cargo light on will turn the other off.
