### ISSUE TITLE
MV-22 Spotlight Disappearing

### ISSUE THREAD

**Issue by Bmoney209** [sw4l/15thsoc#74]
When you are in 3rd person while seated in the MV-22 and you have your spotlight on, some of the surrounding lighting also disappears as well as other MV-22's spotlights. Have not tested this with other aircraft. It does work properly while in 1st person though.

**Comment by Karneck** [comment]
Interesting, no clue what the fix could be, but I'll look into it.

**Comment by MrPiipe** [comment]
Any updates on this? Is this stil happening?
