### ISSUE TITLE
UH1 - Fleet, LPD Deck, Explosion

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#77]
After landing on the LPD and exiting the aircraft, the UH1 may begin to scoot/slide/bounce along the deck of the LPD, eventually resulting in the aircraft exploding on the deck. This bug has existed prior to the latest mod pack update, and I have just been able to reproduce again now after this update.

I've seen this issue result in collision and subsequent explosions with other aircraft on the deck of the LPD during trainings. 

Our current workaround is to simply refrain from leaving our aircraft when we are on the deck of an LPD. If the pilot does leave the aircraft and this behavior does present itself, the pilot can stop it by entering the aircraft again.

Respectfully,

2ndLt J. Leonard
Gunfighter 1-3 AC
HMLA-369 UH-1

**Comment by Fight9** [comment]
Not sure what we can do about this. The LPD has always given problems, as stated. Perhaps a scripted solution is in order? Wheel chocks anyone? eh... skid chocks....

**Comment by armyinf0703** [comment]
I would do a script that can be done when  the helicopter is stopped that links to https://community.bistudio.com/wiki/enableSimulationGlobal. Just have a check that looks for Is helicopter stopped/ engine off, then turn off simulation, if engine is on, engage simulation.

**Comment by Fight9** [comment]
Yeah that's what I had I mind. Might have to work around a few things, but I could lock it into place some way. Just have to figure out the best way to add the option.

**Comment by J-Ziegler** [comment]
Could an object be placed on top of the deck for the aircraft to rest on?

**Comment by Fight9** [comment]
What did you have in mind?

**Comment by J-Ziegler** [comment]
No idea, it's just a thought. Any object that's short (something players could walk on to from the deck) and flat so that the pilots can land on it. I don't know what the issue with the LPD is, but if you don't have to land on it, mission accomplished?

I have no idea if some other custom platform (really it could just be a big rectangle) would perform better.

**Comment by Karneck** [comment]
It's likely stemming from when you are landing on one of the "separated" pieces of the LPD and LHD. As they are broken up into 6 chunks. The have always been funky as balls. I really see no work around for it other then maybe some 2d mission editing work place down invisible concrete (something Geare and I discussed).

**Comment by MrPiipe** [comment]
Any info on this, is this still an issue?

**Comment by EvanWeeks** [comment]
Yes, this is definitely still an issue. If we get out of our bird, the skids will sink into the deck. The moment we get in, the bird bounces a little and explodes.

**Comment by MrPiipe** [comment]
Are you sure you've placed the LPD correctly? Have you tried with one of the operation missions? I haven't seen this bug happen in a loooong time, I believe the error was bad placement on the 2D editor.
