### ISSUE TITLE
AH-1 Laser

### ISSUE THREAD

**Issue by jpwjpw** [sw4l/15thsoc#78]
The laser appears to be colliding with the airframe itself. This one is urgent, as we can no long self-designate our hellfires.

Capt Walsh
Detachment Commander
HMLA-369 "Gunfighters" AH-1

**Comment by jpwjpw** [comment]
Tested this further, and apparently most ACE assets are experiencing the same issue.

**Comment by jpwjpw** [comment]
Any word on this. guys?

**Comment by Karneck** [comment]
It's an ACE3 issue. I haven't been able to get a straight answer about it from them other then that it is "not working correctly".

I will revert the change made and have it be as it once was.

**Comment by Karneck** [comment]
Fixed as it's going to get until ACE3 fix's their end.
