### ISSUE TITLE
M9 optics

### ISSUE THREAD

**Issue by J-Ziegler** [sw4l/15thsoc#79]
Edit from Donado: M9 can use all the optics.

_____________________________________________________________________

Optics can go on the M9. This is silly, though not exactly critical.

My suggestion is to allow all attachments onto the weapon for tacticool implementation of scout snipers.

**Comment by MrPiipe** [comment]
No

**Comment by J-Ziegler** [comment]
I see my attempt at humor was poorly received. However, there is still an issue in the ability to attach scopes to the M9. Specifically the RCO and MRCO.

**Comment by MrPiipe** [comment]
Yeah, was made aware of this. Thought you wanted to add them for some reason..

**Comment by Karneck** [comment]
Its joint Rails.  The M9 wasn't take any optics and now it does. honestly I see no issue with this. It won't ever be used in this manner for our purposes however for those wanting to use it in fun gameplay. Should be able too.
