### ISSUE TITLE
Vehicles - View Centering and TrackIR

### ISSUE THREAD

**Issue by CandidYams** [sw4l/15thsoc#80]
When entering a vehicle, it is possible to skew the center of your view if you have TrackIR enabled and looking off-center. That is, when looking off-center while entering a vehicle, the center of your view once inside the vehicle will be off-center.

I started investigating this issue for the UH-1 since it cropped with the latest update, but I soon noticed that it affects all vehicles.

This may be an ACE3 or Arma issue, considering that it affects all vehicles (modded and vanilla), which is likely out of our control, but I figured it prudent to document here.

Workaround: Pause TrackIR when entering vehicles, or make sure that TrackIR is centered before entering a vehicle. If you encounter this issue you can remove the effect by exiting the vehicle and entering it again with TrackIR centered/paused.

Respectfully,

2ndLt J. Leonard
Gunfighter 1-3 AC
HMLA-369 UH-1

**Comment by Karneck** [comment]
You can do this by holding down CTRL as well. It's an ARMA issue, not a TRACKIR issue and not one we can really do anything about.
