### ISSUE TITLE
Humvee Standing Pos seat issue

### ISSUE THREAD

**Issue by RSFHorn** [sw4l/15thsoc#82]
Two things:

1: Cannot enter this position from outside the vehicle
2: Other seated positions cannot see the person in the standing pos from first person, third person, or from without the vehicle.

**Comment by Karneck** [comment]
For issue 1. Not really a problem.

For issue 2. Yeah thats a problem.

**Comment by Fight9** [comment]
i removed the ffv seat. not worth fixing
