### ISSUE TITLE
LAV & ACE3

### ISSUE THREAD

**Issue by Rockfrog** [sw4l/15thsoc#83]
Our LAV-25A2 has no ACE3 'interaction point'.  This means whilst you can load unconscious units (a self-interaction), you cannot:

Unload unconscious units
Deliver first aid within the vehicle
Repair the vehicle
Access the vehicle's 'ACE3 cargo space'

**Comment by Fight9** [comment]
Are the LAVs our mod? Might have to wait for the dev to update. Chairbourne I think...

**Comment by Karneck** [comment]
LAV is all Chairbourne, nothing I can do with it. I'm sure hes aware of the issue, and he and I are now apart of the CUP team. I'm sure we'll deal with it at some point.
