### ISSUE TITLE
LAV Commander optics

### ISSUE THREAD

**Issue by Rockfrog** [sw4l/15thsoc#84]
The LAV commander optics should be the equal to the gunner's, and one of the very high point tech features of the LAV-25.  High magnification, night vision, multiple thermal vision modes.

The commander optics in the LAV-25A2 version of our mod are literally without worth; extremely short range.  Believe it's due to currently being linked to the pintle mount weapon system.

The commander optics in the LAV-25A1 whist having the appropriate magnification, have no night vision nor thermal modes.  Vehicle unusable at night or low light.

We could mitigate this issue if vehicle commanders could use handheld optics when turned out, but that is also not possible (though would be très cool...).

In-game workaround is for vehicle commander to get out of the vehicle to use personal optics; but clearly that is a very poor option, and dangerous.

As a recon unit, LARs ability to move ahead of the battalion landing team, observe the battlespace, and report up is our primary role.  !broken

**Comment by Fight9** [comment]
Are the LAVs ours? Might have to wait for the dev to update.

**Comment by Karneck** [comment]
This I can fix since we are currently using a tack-on config to make it work for our purposes.

**Comment by Karneck** [comment]
This issue has been fixed. A follow up question has been posted in LAR forums.
