### ISSUE TITLE
ACE 3 People not in corpsman slots unable to use Epi. (Makes CLS Irrelevant)

### ISSUE THREAD

**Issue by Malvandra** [sw4l/15thsoc#85]
People who are not in a corpsman slot are unable to use Epinephrine, which makes CLS useless. Right now as it stands, if our Corpsmen go down, we're utterly fucked.

**Comment by Fight9** [comment]
Might have to give all of our units medical abilities...

attendant = 1; // I think...

**Comment by Karneck** [comment]
I'll see what I can do. However this is mainly an ACE 3 issue.

**Comment by Karneck** [comment]
ACE3 has a setting that fix's this. Closing
