### ISSUE TITLE
Major factions are almost invincible

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#86]
During Spectre's training I decided to spawn a benzeen army guy, apparently the guy is almost invincible, he takes multiple magazines to die, multiple grenades, 2 .50 cal shots, etc..

This is happening with CSAT, NATO, Benzeen Army, 15th Units, Greenfor. Just the guys that have the plate carries, it isn't happening with the jungle militia, jungle rebels and pretty much the guys that don't wear armor.

I'm using the same ACE settings as our operations, I decided to go into the server, run the TF Recon operation, spawned a Benzeen guy and he didn't die, neither did I.

EDIT: Still unsure if it's actually mission setting, since a naked 15th player was invincible while a militia guy was able to die with 2 or 3 shots.

**Comment by MrPiipe** [comment]
Apparently the problem was mission setting.

**Comment by Fight9** [comment]
Possible solution: "Medical Settings [ACE] module > Player damage/AI damage = 50. The damage variable is a multiplier, not a percentage, which means they withstood 50x the normal damage."

http://15thmeu.net/forums/index.php?topic=40824.msg304967#msg304967

**Comment by MrPiipe** [comment]
I'd probably have to guess that it is actually a mission issue, perhaps the LCE op having 20 and people dieing too easily might have been a bug or there was a conflict of some sort. If the issue persists after this weekend and changes have been made, I'll re-open the issue.
