### ISSUE TITLE
mrap replacment - 2 rear seats have weird hand position + expired MRE's

### ISSUE THREAD

**Issue by Moto15th** [sw4l/15thsoc#87]
On the mrap replacement all the seats have really nice looking weapon positions except the rear most 2 seats. Look at the picture to see what I mean, Not game breaking but couldn't stop staring at it during the drive to the op. http://i59.tinypic.com/15psr6a.jpg

Also the MRE's are all expired

**Comment by Fight9** [comment]
FFV seats... non-issue.
