### ISSUE TITLE
AKs can't use flashlights

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#88]
Can't attach flashlights to AKs.

One other suggestion if it's possible for Benzeen Army to have Kobra optics on their weapons, probably randomized so that not all of them are using it or just 1 type of unit, I find it hard to believe that they can afford NVGs but not simple optics such as Kobras.

**Comment by Karneck** [comment]
We'll work on it when we can.

**Comment by MrPiipe** [comment]
Closing this since this is intended by CUP. Will add the Kobra stuff to the AI issues thread.
