### ISSUE TITLE
UH1 - Door gun issues 

### ISSUE THREAD

**Issue by Chewy1007** [sw4l/15thsoc#90]
During some night time testing we discovered that the light source for the flash coming off the guns for the UH-1 appears to be inside the aircraft as opposed to being attached to the guns.  Also, the tracers from the guns are nearly invisible at night, and still faint when viewed through NVGs.

Signed

Capt C. C. Watson 
Detachment Commander
HMLA 369 "Gunfighters" (UH1Y)

**Comment by EvanWeeks** [comment]
Despite the tracers being faint, the muzzle flash is blinding with NVGs on.

**Comment by Karneck** [comment]
I'll look into it, however I am working with the CUP team now and they are helping with doing a huge overhaul on all the Vics. It'll take some time.
