### ISSUE TITLE
M107 is overpowered

### ISSUE THREAD

**Issue by MrPiipe** [sw4l/15thsoc#98]
Not sure what happened to it, but it can destroy T-80s, BMPs, BTRs, with pretty much 1 to 4 bullets.

**Comment by Karneck** [comment]
It's a .50 caliber Rifle. It's meant to destroy engine blocks in armored vehicles, which is what it did before our switch to ACE3. Some adjustment will need to be made, however it is a VERY powerful rifle.

**Comment by Karneck** [comment]
Adjustments have been made. Rifle will still pen armored vehicles to kill crew and destroy engine parts.
